### ISSUE TITLE
Athens on-chain upgrade

### ISSUE THREAD

**Issue by roccomuso** [AndrewKishino/sotez#32]
Does Athens on-chain protocol upgrade requires this lib to be updated in order to be compliant?

**Comment by AndrewKishino** [comment]
There shouldn't be anything required apart from a couple rpc changes such as the `manager_pubkey` change. Changelog can be reviewed at https://blog.nomadic-labs.com/athens-our-proposals-for-the-first-voted-amendment.html.

**Comment by AndrewKishino** [comment]
Those changes are included in the latest release
