### ISSUE TITLE
Error forging zarith NaN

### ISSUE THREAD

**Issue by tuckerchapin** [AndrewKishino/sotez#33]
So I've been trying to spawn a KT1 account from an existing tz account on a ledger, fund it, and delegate this account. 

I've run into a variety of errors -- so I could just be doing this wrong and would appreciate any assistance or insight.

This is roughly what I'm running on `localhost` at the moment:

```javascript
let sotez = new Sotez(
    'https://mainnet-node.tzscan.io',
    'main', 
    'main', 
    { debugMode: true }
);

sotez.importLedger()
    .then(() => {
        return sotez.account({
            amount: 1,
            spendable: true,
            delegatable: true,
            delegate: /*tz36charstringaddress36charstringadd*/,
        });
    })
    .then(
        (res) => console.log(res)
    );
```

I've gotten several different errors with tweaking this code, but this is the one I keep running against and the one that the code currently creates.

The ledger prompts for the public key, I confirm, get some node call/responses from `debugMode` then:

```
Uncaught (in promise) TypeError: Error forging zarith NaN
    at Object.zarith (index.js?4afa:8)
    at Object.op (index.js?4afa:8)
    at eval (index.js?4afa:8)
    at Array.forEach (<anonymous>)
    at eval (index.js?4afa:8)
    at c (index.js?4afa:8)
    at Generator.eval [as _invoke] (index.js?4afa:8)
    at Generator.e.<computed> [as next] (index.js?4afa:8)
    at A (index.js?4afa:8)
    at o (index.js?4afa:8)
```

I feel like there's gotta be something on my end that I'm not getting since I'm very new to both delegation and hardware ledgers.

**Comment by AndrewKishino** [comment]
The example for the account function was not updated. Should be `balance` instead of `amount`. I've updated the documentation to reflect this correctly. Thanks!

**Comment by tuckerchapin** [comment]
Holy shit I'm a dumbass. I had it as `balance` for the longest time but was doing other things incorrectly. At some point I swapped it and didn't notice.

Thank you for the response and this lovely tool.
