### ISSUE TITLE
TypeError: Cannot read property 'publicKeyHash' of undefined

### ISSUE THREAD

**Issue by rajajwaliya** [AndrewKishino/sotez#36]
when i try to active account than i got error

sotez.activate({"tz1UP6NF4LHZxyS8CptqyqqKCuDeZzAvUHyv"}, "edskRoHgaB3edtHCQK6qHrN7ETcZ62gQji3bgHfVmJkvxQbYXPowXgpvPccFCBDwwKm2BFC1SD6z9aGjcGhCFhErgXbCRgEi8v")
  .then((activateOperation) => console.log(activateOperation)).catch(function(e){console.log("error :- "+e)})

**Comment by AndrewKishino** [comment]
The activate method is meant to be used to activate a ICO fundraiser account or a testnet faucet account. You can refer to the [documentation](https://github.com/AndrewKishino/sotez/wiki/Documentation#activate) for how to use this method.
