### ISSUE TITLE
TS2306

### ISSUE THREAD

**Issue by intosKai** [AndrewKishino/sotez#37]
When I'm trying import module in typescript file like in example
```
import Sotez, { utility, forge, crypto, ledger } from 'sotez';
```
I have a error:
```
TS2306: .../node_modules/sotez/dist/types/index.d.ts is not a module
```
How can I fix this or it's wrong from your side?

**Comment by AndrewKishino** [comment]
@intosKai I have pushed a new version 0.5.1 which should correctly import type definitions.
