### ISSUE TITLE
`setDelegate` seems to be attempting to reveal an already revealed address

### ISSUE THREAD

**Issue by tuckerchapin** [AndrewKishino/sotez#51]
```javascript
sotez.setDelegate({delegate: "tz3ZpT9EBzuHguTbhk3svzsgnAbJ8NBzznsR"})
```
 throws an issue with the request to  `https://mainnet.tezrpc.me/chains/main/blocks/head/helpers/preapply/operations`

Request payload:
```json
[ 
   { 
      "branch":"BKvfBkqMNyNrZNzvTpDPD2QNyinX4wYLZJJKiJGmoePMAp72BKu",
      "contents":[ 
         { 
            "kind":"reveal",
            "fee":"1269",
            "public_key":"edpkvYdioa7spPDvjeRGiUTB8r29wfLmjVa55o535cdd6X6qcC3FTf",
            "source":"tz1MajfUukfozAwszhvH5hXYogeax5H7Q557",
            "gas_limit":"10000",
            "storage_limit":"0",
            "counter":"1555427"
         },
         { 
            "kind":"delegation",
            "source":"tz1MajfUukfozAwszhvH5hXYogeax5H7Q557",
            "fee":"1420",
            "gas_limit":"10000",
            "storage_limit":"0",
            "delegate":"tz3ZpT9EBzuHguTbhk3svzsgnAbJ8NBzznsR",
            "counter":"1555428"
         }
      ],
      "protocol":"PsBabyM1eUXZseaJdmXFApDSBqj8YBfwELoxZHHW77EMcAbbwAS",
      "signature":"edsigtx7LywSMZFxUZswYSVk93nggjgZgG92BEkf8fL6PK1SFTWKH4Apahk98djFnZAN9aTtRTocE5b1WmjS5kAruJAJmZCKtbg"
   }
]
```

Response payload 

```json
[ 
   { 
      "kind":"branch",
      "id":"proto.005-PsBabyM1.contract.previously_revealed_key",
      "contract":"tz1MajfUukfozAwszhvH5hXYogeax5H7Q557"
   }
]
```

I'm unclear on the exact issue here or if I'm simply misusing something. It was my understanding that with the upgrade tz* accounts could be delegated from directly.

FWIW, explicitly specifying the source creates the same situation:
```javascript
sotez.setDelegate({ 
    delegate: "tz3ZpT9EBzuHguTbhk3svzsgnAbJ8NBzznsR", 
    source: "tz1MajfUukfozAwszhvH5hXYogeax5H7Q557"
})
```

**Comment by AndrewKishino** [comment]
I'll take a look into the issue. For the time being, can you let me know what version of sotez you are using?

**Comment by AndrewKishino** [comment]
@tuckerchapin My guess is that you may be using an outdated version of sotez. The latest version is 0.5.5 (https://www.npmjs.com/package/sotez). Those fees in your example has changed since which makes be think that upgrading will fix your issue.

**Comment by tuckerchapin** [comment]
Welp, it would look like you are correct. My bad, I thought I upgraded as soon as 0.5.5 was released, but I've been duped by yarn before. Thanks for the prompt feedback though!
