### ISSUE TITLE
Babylonnet\Carthagenet public node URL

### ISSUE THREAD

**Issue by oleiba** [AndrewKishino/sotez#55]
Is there any public RPC node URL for Babylonnet or Carthagenet?
I sued to work with Sotez with `http://alphanet-node.tzscan.io` but it seems out of service currently.

**Comment by AndrewKishino** [comment]
Here are some I have found:

https://carthagenet.SmartPy.io
https://babylonnet.SmartPy.io
http://babylonnet.tezos.cryptium.ch:8732
http://carthagenet.tezos.cryptium.ch:8732
https://babylontest-ssl.tezos.org.ua
https://carthatest-ssl.tezos.org.ua
