### ISSUE TITLE
Invalid private key to public key converter

### ISSUE THREAD

**Issue by ziro-official** [AndrewKishino/sotez#59]
This is the private key and public key generate using bip32:
```
PrivKey : d5d9aefb609d670959daaab7dc06b4c948f13ff30ec6440b5e080a3c340d57dd
PubKey  : 03008d22bc93aab5326866bf0bbb0299bfa0dc195bef7af6cbb8f0cf0a64ae22b6
```
Base 58 encode with prefix
```
private   : "spsk33kCcKpgrvXRQJB2GVGxAMxrSEmwKXLh2KR4ztLcbaCnQq3FFs"
pubkey    : "sppk7bFd7b4DWcabg4yw4N5q8rn9thycWmY21EJDCKfTskNiBH8RJrd"
```

If I import the private to sotez and get pubkey back, it return a incorrect key.
```
await sotez.importKey('spsk33kCcKpgrvXRQJB2GVGxAMxrSEmwKXLh2KR4ztLcbaCnQq3FFs');
console.log(sotez.key._publicKey.toString('hex'))
console.log(sotez.key.publicKey())
```
output is: 
**038d**22bc93aab5326866bf0bbb0299bfa0dc195bef7af6cbb8f0cf0a64ae22b6
CWsEr5NsZNLGN7i3P3J634jWCFoWnzQ1uwe92hYqhRhJUD5Myjyve1

As you can see, it is missing two zero numbers between 3 and 8.
```
03   8d22bc93aab5326866bf0bbb0299bfa0dc195bef7af6cbb8f0cf0a64ae22b6
0300 8d22bc93aab5326866bf0bbb0299bfa0dc195bef7af6cbb8f0cf0a64ae22b6
```

**Comment by AndrewKishino** [comment]
This should be fixed in version `0.6.4`. Thanks for shedding light on the issue. Added tests for this particular case.
