### ISSUE TITLE
Cannot sign transactions after update to 0.7.1

### ISSUE THREAD

**Issue by CherryDT** [AndrewKishino/sotez#64]
I am getting this error:

`[{"kind":"permanent","id":"proto.006-PsCARTHA.operation.invalid_signature"}]`

Before I updated to 0.7.1, I was using 0.6.2 with my fix for #60. Do you see any reason why it would have stopped working in 0.7.1? Are there any signature-related changes that would explain why suddenly I cannot sign transactions?

I am creating a client and then calling `await client.importKey(secretKey)` as before. The `secretKey` is a string starting with `edsk`. It works after downgrading to 0.6.3.

**Comment by AndrewKishino** [comment]
Nothing should have changed from the importing and signing flow. I've started tracking the [CHANGELOG](https://github.com/AndrewKishino/sotez/blob/master/CHANGELOG.md) between versions and there have been some updates, but shouldn't affect the signing. Sotez is no longer exported by default so you will have to import as:

```
import { Sotez } from 'sotez';
```

Do you mind sharing the operation you are signing and the signature?

**Comment by AndrewKishino** [comment]
@CherryDT I have pushed a new version `0.7.2` which should address the bug you were experiencing.

**Comment by CherryDT** [comment]
Thank you very much!
